# Default Values
substitutions:
  _SERVICE_NAME: master-debater
  _REGION: europe-west1 # Deployment region for the service
  _ARTIFACT_REGION: europe # Multi-region endpoint for Europe in Artifact Registry
  _PROJECT_ID: master-debater # Your Google Cloud Project ID
  _REPOSITORY: eu-artifact-registry # Name of your Artifact Registry repository
  _SERVICE_SUFFIX: '' # by default deploy to a side deployment; override in the Cloud Build config

steps:
  ### Build
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_ARTIFACT_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}", "."]

  ### Push
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_ARTIFACT_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"]

  ### Deploy
  - id: "deploy prod service"
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}${_SERVICE_SUFFIX}'
      - '--image=${_ARTIFACT_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated' # double check auth works before going live with this setting
      - '--update-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,OPENAI_ORG_ID=OPENAI_ORG_ID:latest'
      - '--tag=${BRANCH_NAME}'
